### ISSUE TITLE
Make Javascript error messages more useful

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-requests#394]
"[HTML] Uncaught Error" is not very useful without a stack trace.

**Comment by robotboy655** [comment]
But they do?

**Comment by Bo98** [comment]
Oh I got it to work now. I have no idea why it didn't before.

Anyway I'll turn this into a request to make the messages more useful (like a stack trace).

**Comment by robotboy655** [comment]
But they do? You can see it for example here:
https://github.com/Facepunch/garrysmod-issues/issues/689

**Comment by Bo98** [comment]
Seems to print the stack trace for some things but not all. For example creating a random syntax error in the menu only prints the stack trace for one error:

```
[HTML] Uncaught SyntaxError: Unexpected token )
[HTML] Uncaught ReferenceError: IN_ENGINE is not defined
[HTML] Uncaught ReferenceError: App is not defined
[HTML] Uncaught ReferenceError: App is not defined
[HTML] Uncaught ReferenceError: App is not defined
[HTML] Uncaught ReferenceError: App is not defined
[HTML] Uncaught ReferenceError: App is not defined
[HTML] Uncaught ReferenceError: App is not defined
[HTML] Uncaught ReferenceError: IN_ENGINE is not defined
[HTML] Uncaught Error: [$injector:modulerr] Failed to instantiate module MenuApp due to:
Error: [$injector:nomod] Module 'MenuApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.8/$injector/nomod?p0=MenuApp
    at asset://garrysmod/html/js/thirdparty/angular.js:63:12
    at asset://garrysmod/html/js/thirdparty/angular.js:1764:17
    at ensure (asset://garrysmod/html/js/thirdparty/angular.js:1688:38)
    at module (asset://garrysmod/html/js/thirdparty/angular.js:1762:14)
    at asset://garrysmod/html/js/thirdparty/angular.js:4094:22
    at forEach (asset://garrysmod/html/js/thirdparty/angular.js:323:20)
    at loadModules (asset://garrysmod/html/js/thirdparty/angular.js:4078:5)
    at createInjector (asset://garrysmod/html/js/thirdparty/angular.js:4004:11)
    at asset://garrysmod/html/js/thirdparty/angular.js:1446:20
    at bootstrap (asset://garrysmod/html/js/thirdparty/angular.js:1467:12)
http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=MenuApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'MenuApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.8%2F%24injector%2Fnomod%3Fp0%3DMenuApp%0A%20%20%20%20at%20asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A1764%3A17%0A%20%20%20%20at%20ensure%20(asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A1688%3A38)%0A%20%20%20%20at%20module%20(asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A1762%3A14)%0A%20%20%20%20at%20asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A4094%3A22%0A%20%20%20%20at%20forEach%20(asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A4078%3A5)%0A%20%20%20%20at%20createInjector%20(asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A4004%3A11)%0A%20%20%20%20at%20asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A1446%3A20%0A%20%20%20%20at%20bootstrap%20(asset%3A%2F%2Fgarrysmod%2Fhtml%2Fjs%2Fthirdparty%2Fangular.js%3A1467%3A12)
[HTML] Uncaught TypeError: Cannot set property 'Version' of undefined
[HTML] Uncaught TypeError: Cannot set property 'Languages' of undefined
[HTML] Uncaught TypeError: Cannot set property 'Language' of undefined
[HTML] Uncaught TypeError: Cannot set property 'Gamemodes' of undefined
[HTML] Uncaught TypeError: Cannot read property 'Gamemode' of undefined
[HTML] Uncaught TypeError: Cannot set property 'Games' of undefined
[HTML] Uncaught TypeError: Cannot call method 'Update' of undefined
[HTML] Uncaught TypeError: Cannot set property 'InGame' of undefined
[HTML] Uncaught TypeError: Cannot set property '1' of undefined
```

**Comment by willox** [comment]
Fixed in the dev branch.
![2016-01-10_01-43-32](https://cloud.githubusercontent.com/assets/1499676/12219616/0737bbe2-b743-11e5-93f8-a9df41ba2a4c.png)

**Comment by Bo98** [comment]
Thanks.

**Comment by zerfgog** [comment]
no problem
